/**
 * Production-grade artifact generators (v2.9).
 *
 * The base agent-deploy/index.ts emits the planning artifacts; this module
 * adds artifacts required for production-grade delivery:
 *
 *   1. Dockerfile (reproducible build with pinned versions)
 *   2. kubernetes/deployment.yaml (resource limits + probes)
 *   3. kubernetes/service.yaml + kubernetes/hpa.yaml (autoscaling)
 *   4. prometheus-rules.yaml (SLA + cost + quality alerts)
 *   5. grafana-dashboard.json (observability)
 *   6. runbook.md (on-call response)
 *   7. rollback-plan.md (failure recovery procedure)
 *   8. provenance.json (versioned everything for replay)
 *   9. license-audit.md (compliance check)
 *  10. cost-governance.md (budget caps + drift alerts)
 *  11. production-checklist.md (gating checklist before deploy)
 *  12. sbom.json (software bill of materials)
 *
 * Maps to the production-grade requirements outlined in
 * docs/superpowers/specs/2026-05-02-agent-e2e-sample.md.
 */

interface DeploymentPlan {
  input: { model: string; hardware: string; workload: string; target_cost?: number; target_ttft_ms?: number };
  parsed_model: { hf_id: string; archetype: string; total_params_b: number; active_params_b: number; num_layers: number; max_context: number; num_experts: number };
  hardware: { id: string; name: string; vendor: { id: string }; memory: { capacity_gb: { value: number } } };
  recommended: { engine: string; quantization: string; parallelism: { tp: number; pp: number; ep: number }; card_count: number; expected_decode_tok_s_per_card: number; estimated_dollars_per_m_tokens: number };
  kernel_gaps: Array<{ op: string; missing_on: string; suggestion: string }>;
}

const ENGINE_DOCKER_BASE: Record<string, { image: string; tag_pinned: string; entrypoint: string; setup: string }> = {
  vllm: {
    image: 'vllm/vllm-openai',
    tag_pinned: 'v0.6.4',
    entrypoint: '/usr/local/bin/python3 -m vllm.entrypoints.openai.api_server',
    setup: '# vLLM image ships with CUDA + flash-attn pre-installed\n'
  },
  sglang: {
    image: 'lmsysorg/sglang',
    tag_pinned: 'v0.4.0-cu124',
    entrypoint: '/usr/local/bin/python3 -m sglang.launch_server',
    setup: '# SGLang image ships with vLLM compat + flashinfer\n'
  },
  'tensorrt-llm': {
    image: 'nvcr.io/nvidia/tensorrt-llm/release',
    tag_pinned: '0.14.0',
    entrypoint: '/usr/local/bin/trtllm-serve',
    setup: '# TRT-LLM image ships with engine compile toolchain\n'
  },
  mindie: {
    image: 'ascendhub.huawei.com/public-ai/mindie',
    tag_pinned: '1.0.RC3-910C',
    entrypoint: '/usr/local/Ascend/mindie/latest/bin/mindie-server',
    setup: '# MindIE image — ASCEND_RT_VISIBLE_DEVICES required at runtime\n'
  },
  lmdeploy: {
    image: 'openmmlab/lmdeploy',
    tag_pinned: 'v0.6.0-cu12',
    entrypoint: '/usr/local/bin/python3 -m lmdeploy serve api_server',
    setup: '# LMDeploy image with TurboMind backend\n'
  }
};

export function generateDockerfile(plan: DeploymentPlan): string {
  const e = ENGINE_DOCKER_BASE[plan.recommended.engine];
  if (!e) {
    return `# No Dockerfile template for engine ${plan.recommended.engine} — add to ENGINE_DOCKER_BASE in production-artifacts.ts`;
  }

  return `# Dockerfile generated by agent-deploy (production-grade)
# Model: ${plan.parsed_model.hf_id}
# Engine: ${plan.recommended.engine} ${e.tag_pinned}
# Hardware: ${plan.hardware.name} × ${plan.recommended.card_count}
#
# This is a reproducible build — version-pinned base + deps. For air-gapped
# deployment, mirror the base image to your registry.

FROM ${e.image}:${e.tag_pinned}

# Reproducibility: pin model checkpoint by commit SHA at deploy time
# (replace HEAD with the actual commit hash from the model repo's git log)
ARG MODEL_REVISION=HEAD

# Create non-root runtime user
RUN useradd -m -u 1000 -s /bin/bash llm-runtime
USER llm-runtime
WORKDIR /workspace

${e.setup}
# Pre-fetch model weights — done at build time for cold-start reduction.
# For models > 100GB, consider mounting from PVC instead.
ARG MODEL_ID=${plan.parsed_model.hf_id}
RUN python3 -c "from huggingface_hub import snapshot_download; \\
                snapshot_download(repo_id='\${MODEL_ID}', revision='\${MODEL_REVISION}', \\
                                  local_dir='/workspace/model', local_dir_use_symlinks=False)" \\
    || echo "Model download failed — must mount /workspace/model as volume"

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=120s --retries=3 \\
  CMD curl -f http://localhost:8000/health || exit 1

EXPOSE 8000

ENV PYTHONUNBUFFERED=1
ENV LOG_LEVEL=info

# Engine launch — reads from env to allow rollout-time tuning
ENTRYPOINT ["${e.entrypoint}"]
CMD ["--model-path", "/workspace/model", \\
     "--tp-size", "${plan.recommended.parallelism.tp}", \\
     "--quantization", "${plan.recommended.quantization}", \\
     "--port", "8000"]
`;
}

export function generateK8sDeployment(plan: DeploymentPlan): string {
  const r = plan.recommended;
  const m = plan.parsed_model;
  const slug = m.hf_id.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 50);
  const gpuVendor = plan.hardware.vendor.id;
  const gpuResource = gpuVendor === 'nvidia' ? 'nvidia.com/gpu'
    : gpuVendor === 'amd' ? 'amd.com/gpu'
    : gpuVendor === 'huawei' ? 'huawei.com/Ascend910'
    : `${gpuVendor}.com/gpu`;

  return `# Generated by agent-deploy (production-grade)
# Apply: kubectl apply -f deployment.yaml -f service.yaml -f hpa.yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${slug}-server
  labels:
    app: ${slug}
    managed-by: agent-deploy
    model-archetype: ${m.archetype}
    hardware-class: ${plan.hardware.id}
    quantization: ${r.quantization}
spec:
  replicas: 1   # scale via HPA after warmup
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  # zero-downtime rollouts
  selector:
    matchLabels: { app: ${slug} }
  template:
    metadata:
      labels:
        app: ${slug}
        model-archetype: ${m.archetype}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      # Pin to specific arch / generation
      nodeSelector:
        accelerator: "${plan.hardware.id}"

      # Restart only on actual failure; respect graceful shutdown for KV cache flush
      terminationGracePeriodSeconds: 60

      containers:
      - name: ${r.engine}
        image: ${slug}:${r.engine}-${r.quantization}-tp${r.parallelism.tp}
        imagePullPolicy: IfNotPresent

        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef: { name: hf-token, key: token, optional: true }
        - name: ENGINE_LOG_LEVEL
          value: "info"
        - name: PROMETHEUS_MULTIPROC_DIR
          value: "/tmp/prom"

        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: metrics

        resources:
          requests:
            cpu: "8"
            memory: "${Math.ceil(plan.hardware.memory.capacity_gb.value * 0.5)}Gi"
            ${gpuResource}: "${r.parallelism.tp}"
          limits:
            cpu: "16"
            memory: "${Math.ceil(plan.hardware.memory.capacity_gb.value * 0.7)}Gi"
            ${gpuResource}: "${r.parallelism.tp}"

        # Long startup — model loads can take 5-15 minutes
        startupProbe:
          httpGet: { path: /health, port: 8000 }
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 30   # 15 min total startup budget

        readinessProbe:
          httpGet: { path: /health, port: 8000 }
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        livenessProbe:
          httpGet: { path: /health, port: 8000 }
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3

        volumeMounts:
        - name: model-weights
          mountPath: /workspace/model
          readOnly: true
        - name: dshm
          mountPath: /dev/shm   # NCCL + PyTorch shared memory
        - name: prom-multiproc
          mountPath: /tmp/prom

      volumes:
      - name: model-weights
        persistentVolumeClaim:
          claimName: ${slug}-weights-pvc
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 16Gi
      - name: prom-multiproc
        emptyDir: {}

      # Anti-affinity to avoid co-scheduling replicas on the same node
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - { key: app, operator: In, values: [${slug}] }
              topologyKey: kubernetes.io/hostname

---
# Service (cluster-internal stable endpoint)
apiVersion: v1
kind: Service
metadata:
  name: ${slug}-svc
  labels: { app: ${slug} }
spec:
  type: ClusterIP
  selector: { app: ${slug} }
  ports:
  - { name: http, port: 80, targetPort: 8000 }
  - { name: metrics, port: 8001, targetPort: 8000 }

---
# HorizontalPodAutoscaler (scale by request queue depth)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${slug}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${slug}-server
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Pods
    pods:
      metric: { name: vllm_request_queue_size }
      target: { type: AverageValue, averageValue: "20" }
  - type: Pods
    pods:
      metric: { name: gpu_compute_utilization_pct }
      target: { type: AverageValue, averageValue: "75" }
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - { type: Percent, value: 50, periodSeconds: 60 }
    scaleDown:
      stabilizationWindowSeconds: 300   # cool down before scale-down
      policies:
      - { type: Pods, value: 1, periodSeconds: 120 }
`;
}

export function generatePrometheusRules(plan: DeploymentPlan): string {
  const r = plan.recommended;
  const m = plan.parsed_model;
  const slug = m.hf_id.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 50);
  const ttft_target_ms = plan.input.target_ttft_ms ?? 500;
  const cost_target = plan.input.target_cost ?? r.estimated_dollars_per_m_tokens * 1.2;

  return `# Prometheus alert rules — generated by agent-deploy
# Apply: kubectl apply -f prometheus-rules.yaml
groups:
- name: ${slug}-sla
  interval: 30s
  rules:

  # ===== SLA: latency =====
  - alert: TTFT_p99_too_high
    expr: histogram_quantile(0.99, rate(vllm_e2e_request_latency_seconds_bucket{deployment="${slug}"}[5m])) > ${ttft_target_ms / 1000}
    for: 5m
    labels: { severity: warning, sla: latency }
    annotations:
      summary: "TTFT p99 above SLA target"
      description: "p99 = {{ $value }}s, target = ${ttft_target_ms / 1000}s. Check engine queue depth + cold prefill cache."
      runbook: "/runbook.md#ttft-p99"

  - alert: Decode_throughput_dropped
    expr: rate(vllm_generation_tokens_total{deployment="${slug}"}[5m]) < ${Math.floor(r.expected_decode_tok_s_per_card * r.parallelism.tp * 0.7)}
    for: 10m
    labels: { severity: warning, sla: throughput }
    annotations:
      summary: "Decode throughput below 70% of expected"
      description: "Achieved {{ $value }} tok/s (per pod), expected ${Math.floor(r.expected_decode_tok_s_per_card * r.parallelism.tp)}. Check HBM bandwidth utilization."

  # ===== SLA: error rate =====
  - alert: Request_error_rate_high
    expr: rate(vllm_request_failures_total{deployment="${slug}"}[5m]) / rate(vllm_request_total{deployment="${slug}"}[5m]) > 0.01
    for: 5m
    labels: { severity: critical, sla: errors }
    annotations:
      summary: "Error rate > 1%"
      runbook: "/runbook.md#error-rate"

  # ===== Resource: OOM =====
  - alert: GPU_OOM_imminent
    expr: gpu_memory_used_bytes{deployment="${slug}"} / gpu_memory_total_bytes > 0.95
    for: 2m
    labels: { severity: warning, sla: memory }
    annotations:
      summary: "GPU memory > 95% — OOM imminent"
      description: "Reduce max-num-seqs or increase gpu-memory-utilization headroom."
      runbook: "/runbook.md#gpu-oom"

  - alert: GPU_OOM_actual
    expr: increase(gpu_oom_events_total{deployment="${slug}"}[10m]) > 0
    for: 1m
    labels: { severity: critical, sla: memory }
    annotations:
      summary: "Actual OOM event detected"
      runbook: "/runbook.md#gpu-oom"

  # ===== Cost governance =====
  - alert: Cost_per_M_tokens_above_budget
    expr: (sum(gpu_power_watts{deployment="${slug}"}) / 1000 * 0.10 + ${r.card_count} * 3.50) / (sum(rate(vllm_generation_tokens_total{deployment="${slug}"}[1h])) * 3600 / 1e6) > ${cost_target}
    for: 30m
    labels: { severity: warning, sla: cost }
    annotations:
      summary: "$/M tokens above budget target"
      description: "Current ~{{ $value }} \\$/M tok, target = ${cost_target} \\$/M tok. Workload mix may have drifted."

  # ===== Deployment health =====
  - alert: Deployment_unhealthy
    expr: kube_deployment_status_replicas_available{deployment="${slug}-server"} < kube_deployment_spec_replicas{deployment="${slug}-server"}
    for: 5m
    labels: { severity: critical }
    annotations:
      summary: "Replicas not at desired count"
      runbook: "/runbook.md#deployment-unhealthy"

  # ===== Quality drift (advanced — only if eval-as-service is wired up) =====
  - alert: Quality_eval_drift
    expr: abs(eval_score{deployment="${slug}", set="${plan.input.workload}-suite"} - eval_score_baseline{deployment="${slug}", set="${plan.input.workload}-suite"}) > 0.005
    for: 1h
    labels: { severity: warning, sla: quality }
    annotations:
      summary: "Eval score drift > 0.5% from baseline"
      description: "Trigger rollback if drift persists 2 evaluation cycles."
      runbook: "/runbook.md#quality-drift"
`;
}

export function generateRunbook(plan: DeploymentPlan): string {
  const m = plan.parsed_model;
  const r = plan.recommended;
  return `# On-Call Runbook for ${m.hf_id} on ${plan.hardware.name}

> Generated by agent-deploy. Pair with prometheus-rules.yaml + rollback-plan.md.

## Quick reference

| Metric | Target | Alert threshold |
|---|---|---|
| TTFT p99 | ≤ ${plan.input.target_ttft_ms ?? 500}ms | TTFT_p99_too_high |
| Decode tok/s/card | ≥ ${r.expected_decode_tok_s_per_card.toFixed(0)} | Decode_throughput_dropped |
| Error rate | < 1% | Request_error_rate_high |
| $/M tokens | ≤ ${(plan.input.target_cost ?? r.estimated_dollars_per_m_tokens * 1.2).toFixed(2)} | Cost_per_M_tokens_above_budget |
| GPU memory | < 95% | GPU_OOM_imminent |
| Eval drift | < 0.5% | Quality_eval_drift |

## Common alerts

### \`TTFT_p99_too_high\`

**Likely causes**:
1. Cold prefix cache (just deployed / cache evicted)
2. Burst of long-prompt requests
3. Pod memory pressure causing swapping

**First-response (5 min)**:
\`\`\`bash
# Check engine queue depth
kubectl exec -it deploy/${m.hf_id.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-server -- curl localhost:8000/metrics | grep queue_size

# Check GPU memory
kubectl exec -it deploy/${m.hf_id.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-server -- nvidia-smi
\`\`\`

**Mitigation**:
- If queue > 50: temporarily increase \`--max-num-seqs\` (engine restart req)
- If GPU mem > 90%: KV-quant FP8 → free up cache
- If long-prompt burst: enable \`--enable-chunked-prefill\` if not already

**Escalate** if persistent > 30 min: trigger rollback (see rollback-plan.md).

### \`GPU_OOM_imminent\` or \`GPU_OOM_actual\`

**Likely causes**:
1. KV cache full (concurrent users × ctx_len > budget)
2. Memory leak in custom kernels
3. Model weight + activation > expected (prompt of unexpected shape)

**First-response (2 min)**:
\`\`\`bash
# Reduce max concurrent requests immediately
kubectl set env deploy/${m.hf_id.replace(/[^a-z0-9]+/gi, '-').toLowerCase()}-server MAX_NUM_SEQS=128
\`\`\`

**Mitigation**:
- Enable KV-cache CPU offload (pattern: hot-cold-kv-tiering)
- Reduce max-model-len if some users don't need full ${m.max_context} tokens
- If OOM persists: rollback + investigate

### \`Quality_eval_drift\`

**Likely causes**:
1. Quantization regression (workload mix shifted to long-context where ${r.quantization} is weaker)
2. Engine bug (recent vLLM/SGLang upgrade)
3. Model corruption / wrong checkpoint loaded

**First-response (15 min)**:
\`\`\`bash
# Verify checkpoint sha matches expected
kubectl exec -it ... -- sha256sum /workspace/model/model.safetensors
# Compare to provenance.json
\`\`\`

**Mitigation**:
- If sha mismatch → critical, rollback immediately
- If sha matches → consider quant rollback (FP4 → FP8 → FP16) per migration playbook
- Run full eval suite + flag for manual review

### \`Cost_per_M_tokens_above_budget\`

Workload mix has likely shifted. Not necessarily an immediate emergency.

**First-response (30 min)**:
- Check workload distribution: short-chat vs long-context vs reasoning
- If long-context grew: cost is structural (longer ctx = more KV reads = more bandwidth)
- If short-chat grew with low concurrency: check batch-size effective utilization

**Mitigation**:
- Tune chunked-prefill chunk size for current workload
- Consider PD-disagg if scale > 16 cards
- Engineer-of-record review monthly

## Diagnostic commands

\`\`\`bash
# Engine state
kubectl exec -it deploy/<name> -- curl localhost:8000/metrics | grep -E "queue|cache|throughput"

# GPU state
kubectl exec -it deploy/<name> -- ${plan.hardware.vendor.id === 'nvidia' ? 'nvidia-smi' : plan.hardware.vendor.id === 'amd' ? 'rocm-smi' : 'npu-smi info'}

# Recent logs (last 5 min)
kubectl logs deploy/<name> --since=5m | grep -iE "error|warn|oom"

# Pod resource use
kubectl top pod -l app=<name>
\`\`\`

## Profiling (when issue is "slow but not failing")

Use ${plan.hardware.vendor.id === 'nvidia' ? '\`ncu\` (deep) or \`nsys\` (timeline)' : plan.hardware.vendor.id === 'amd' ? '\`rocprof\`' : plan.hardware.vendor.id === 'huawei' ? '\`msprof\` (Cube/Vector pipeline view)' : 'vendor profiler'}.

See /dev-toolkit/profiling-tools/ for invocation examples.

## Escalation

| Severity | Action |
|---|---|
| Critical (data loss / outage) | Page primary on-call. Trigger rollback immediately. |
| High (SLA breach > 30 min) | Page primary on-call. |
| Warn (drift / cost) | File ticket; review next morning. |
`;
}

export function generateRollbackPlan(plan: DeploymentPlan): string {
  const m = plan.parsed_model;
  const slug = m.hf_id.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '').slice(0, 50);
  return `# Rollback Plan for ${m.hf_id}

> Generated by agent-deploy. Triggered by runbook on critical SLA breach.

## Rollback budget: 5 minutes (DNS/LB) or 2 minutes (canary weight)

## Pre-flight requirements (must be true BEFORE deploy)

- [x] Old stack remains on standby (DO NOT tear down for ≥ 14 days post-deploy)
- [x] Old stack receives mirror traffic for monitoring
- [x] DNS / LB has weighted routing configured
- [x] Engineer-of-record knows the rollback command
- [x] Last-known-good engine version + model checkpoint pinned

## Rollback procedures (by deployment style)

### A. Kubernetes weighted Service routing

\`\`\`bash
# Shift 100% to old stack
kubectl patch svc ${slug}-svc -p '{"spec":{"selector":{"version":"old"}}}'

# Verify
kubectl get pods -l version=old
curl ${slug}-svc:80/health
\`\`\`

### B. Istio VirtualService (canary weights)

\`\`\`yaml
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata: { name: ${slug} }
spec:
  http:
  - route:
    - destination: { host: ${slug}-svc, subset: old }
      weight: 100      # was 0% before; now 100%
    - destination: { host: ${slug}-svc, subset: new }
      weight: 0        # was 100% before
\`\`\`

### C. DNS-based (slowest, last resort)

Update DNS A/CNAME record to old stack endpoint. **TTL must be ≤ 60s** (configured at deploy time).

## Verification after rollback

- [ ] TTFT p99 returns to baseline within 5 min
- [ ] Error rate drops below 1% within 5 min
- [ ] No user-facing complaints in next 30 min

## Post-incident actions

1. Open incident ticket with timeline + rollback decision rationale
2. Snapshot the new-stack state (logs / metrics / dashboards) — DO NOT delete pods immediately
3. Schedule post-mortem within 5 business days
4. Update runbook with new failure mode if novel
5. Decision: re-roll-out (after fix) vs. retire stack (if fundamental issue)

## Standby stack lifecycle

- **Day 0-14**: Old stack runs at 0% traffic but full capacity (cost ~ same as new stack)
- **Day 14-30**: Old stack scaled to minimum (1 pod) for emergency fallback
- **Day 30+**: Old stack torn down. Re-deploy from CI if needed.
`;
}

export function generateProvenance(plan: DeploymentPlan): string {
  const m = plan.parsed_model;
  const r = plan.recommended;
  return JSON.stringify({
    schema_version: '1.0',
    generated_at: new Date().toISOString(),
    purpose: 'Replay-able deployment provenance for audit + reproducibility. Pair with sbom.json.',

    model: {
      hf_id: m.hf_id,
      revision: 'TODO_PIN_TO_COMMIT_SHA',
      checkpoint_sha256: 'TODO_COMPUTE_AT_FETCH_TIME',
      license: 'TODO_FROM_HF_API',
      total_params_b: m.total_params_b,
      active_params_b: m.active_params_b,
      archetype: m.archetype
    },

    hardware: {
      id: plan.hardware.id,
      name: plan.hardware.name,
      vendor: plan.hardware.vendor.id,
      hbm_per_card_gb: plan.hardware.memory.capacity_gb.value,
      card_count: r.card_count,
      driver_version: 'TODO_PIN',
      firmware: 'TODO_PIN'
    },

    engine: {
      id: r.engine,
      version: 'TODO_PIN',     // e.g., 'vllm:0.6.4'
      image_sha256: 'TODO_COMPUTE_FROM_CONTAINER_REGISTRY'
    },

    quantization: {
      format: r.quantization,
      calibration_set: 'TODO_IF_USED',
      calibration_samples: 0
    },

    parallelism: r.parallelism,

    kernel_libraries: {
      cublas_version: 'TODO_PIN',
      cudnn_version: 'TODO_PIN',
      flash_attn_version: 'TODO_PIN',
      tensor_rt_version: r.engine === 'tensorrt-llm' ? 'TODO_PIN' : null
    },

    deployment_target: {
      kubernetes_version: 'TODO_PIN',
      container_runtime: 'TODO_PIN',
      gpu_operator_version: 'TODO_PIN'
    },

    expected_baseline: {
      decode_tok_s_per_card: r.expected_decode_tok_s_per_card,
      dollars_per_m_tokens: r.estimated_dollars_per_m_tokens,
      ttft_p99_target_ms: plan.input.target_ttft_ms ?? null
    },

    audit_trail: {
      generator: 'evokernel-spec/scripts/agent-deploy v2.9',
      generator_commit: 'TODO_GIT_REV_PARSE_HEAD',
      corpus_version: 'TODO_FROM_API_INDEX',
      operator_engineer: 'TODO_AT_DEPLOY_TIME',
      approval_chain: []
    }
  }, null, 2);
}

export function generateLicenseAudit(plan: DeploymentPlan): string {
  const m = plan.parsed_model;
  const r = plan.recommended;
  return `# License Audit for ${m.hf_id} on ${plan.hardware.name}

> Generated by agent-deploy. **Manual review required before production deployment.**

## Model license

- **Source**: HuggingFace \`${m.hf_id}\`
- **License**: TODO — fetch from HF API or LICENSE file in repo
- **Commercial use**: TODO — verify against your use case
- **Attribution**: TODO — check terms

### Common gotchas
- Llama / Llama 4: Custom Meta license — has commercial use clause
- Qwen: Tongyi Qianwen license — China-specific clauses
- DeepSeek: MIT (model weights) but specific terms in model card
- Mistral: Apache 2.0 for some, restrictive for others (Mistral Large 2)

## Engine license

- **Engine**: ${r.engine}
- **License**: ${r.engine === 'vllm' ? 'Apache 2.0' : r.engine === 'sglang' ? 'Apache 2.0' : r.engine === 'tensorrt-llm' ? 'NVIDIA proprietary (binary)' : r.engine === 'mindie' ? 'Huawei proprietary' : 'TODO'}

## Kernel library licenses (transitive)

| Library | License | Risk |
|---|---|---|
| cuBLAS / cuDNN | NVIDIA EULA | Binary OK in container |
| CUTLASS | Apache 2.0 | OK |
| flash-attention | BSD-3 | OK |
| ROCm libs | MIT | OK |
| MindIE / aclnn | Huawei proprietary | Binary OK |

## Compliance checklist (production gate)

- [ ] Model license terms reviewed by legal
- [ ] Engine license matches deployment context (cloud / on-prem / air-gapped)
- [ ] All transitive deps documented in sbom.json
- [ ] Attribution shown to end users where required
- [ ] Data residency policy (does training data restrict deployment region?)
- [ ] Export controls reviewed (EAR / EU dual-use for some models + hardware)

## Action items
- Replace all TODOs in this file with actual values from HF API + repo LICENSE files
- Have legal team sign off before initial deploy
- Re-audit annually or on model upgrade
`;
}

export function generateProductionChecklist(plan: DeploymentPlan): string {
  const m = plan.parsed_model;
  const r = plan.recommended;
  return `# Production Readiness Checklist — ${m.hf_id} on ${plan.hardware.name}

> Generated by agent-deploy. **Every item must be checked off before initial production deploy.**

## 1. Model & License (8 items)

- [ ] Model license reviewed by legal (see license-audit.md)
- [ ] Model checkpoint SHA-256 pinned in provenance.json
- [ ] Eval baseline established (${plan.input.workload}-suite scores recorded)
- [ ] Inference output spot-checked by domain expert (100 sample req)
- [ ] No PII / sensitive data in any prompt template
- [ ] Refusal / safety alignment tested (jailbreak resistance)
- [ ] Token-level reproducibility verified (same prompt + seed → same output)
- [ ] Long-context behavior tested (128K+ if applicable to ${m.max_context})

## 2. Hardware & Capacity (6 items)

- [ ] HBM headroom > 10% under p99 concurrent load
- [ ] Power budget per rack < PDU limit
- [ ] Cooling: ${plan.hardware.id.startsWith('b2') || plan.hardware.id.startsWith('b3') || plan.hardware.id.includes('mi355') ? 'liquid cooling verified' : 'air cooling sufficient'}
- [ ] Network: NCCL all-reduce baseline measured (must be > 80% theoretical)
- [ ] Storage: model weights pre-fetched to PVC; cold-start < 5 min
- [ ] Multi-GPU: ${r.parallelism.tp > 1 ? 'NCCL topology verified, all-reduce < 1ms intra-node' : 'single-GPU only'}

## 3. Engine & Configuration (8 items)

- [ ] Engine version pinned in Dockerfile + provenance.json
- [ ] Quantization format (${r.quantization}) verified to pass full eval suite
- [ ] CUDA Graph / equivalent enabled (\`--enforce-eager\` removed)
- [ ] Continuous batching enabled
- [ ] Chunked prefill enabled if mixed prefill/decode workload
- [ ] Prefix caching enabled if workload has > 30% prefix overlap
- [ ] Speculative decoding tested (independently of quantization)
- [ ] Engine config matches launch.sh exactly (no last-minute tweaks)

## 4. Observability (8 items)

- [ ] Prometheus scraping configured (port 8000 \`/metrics\`)
- [ ] Grafana dashboards imported (engine + GPU + cost)
- [ ] Alerts wired to PagerDuty / Slack / email
- [ ] Distributed tracing (NVTX / vendor equivalent) in place for prefill/decode phases
- [ ] Log aggregation (Loki / ELK) capturing all pod logs with retention ≥ 30 days
- [ ] Audit log of all changes captured to immutable storage
- [ ] On-call rotation defined; primary + secondary
- [ ] Runbook tested in staging (chaos test: kill pod, verify recovery)

## 5. SLA & Cost (6 items)

- [ ] TTFT p99 SLA agreed: ≤ ${plan.input.target_ttft_ms ?? 'TBD'}ms
- [ ] Throughput SLA agreed: ≥ ${r.expected_decode_tok_s_per_card.toFixed(0)} tok/s/card
- [ ] Error budget defined (e.g., < 1% / month)
- [ ] Cost target: ≤ ${plan.input.target_cost?.toFixed(2) ?? 'TBD'} \$/M tokens
- [ ] Cost alert threshold = 1.2× target
- [ ] Monthly cost review scheduled

## 6. Security (8 items)

- [ ] Container runs as non-root user
- [ ] Secrets via Kubernetes secrets (not env vars); HF_TOKEN, etc.
- [ ] Image scanned for CVEs (Trivy / Grype) — no critical findings
- [ ] Network policies restrict pod ingress / egress
- [ ] TLS termination at ingress
- [ ] API authentication (JWT / API key / mTLS)
- [ ] Rate limiting per client
- [ ] DDoS mitigation upstream

## 7. Resilience (6 items)

- [ ] Rollback procedure tested (rollback-plan.md)
- [ ] Standby stack ready for 14+ days post-deploy
- [ ] Pod anti-affinity prevents single-node failure → outage
- [ ] HPA tested under load
- [ ] Graceful shutdown verified (in-flight requests complete)
- [ ] Disaster recovery: backup + restore tested

## 8. Lifecycle (4 items)

- [ ] Deprecation policy: how to retire this deployment in future
- [ ] Model upgrade path documented (Llama 4 → 4.5 procedure)
- [ ] Engine upgrade path documented (vLLM 0.6 → 0.7)
- [ ] Sunset criteria defined (when does this deployment stop being supported?)

## Sign-off

Before initial deploy, the following must sign off:

- [ ] Engineering lead — technical correctness
- [ ] Operations lead — runbook + on-call coverage
- [ ] Security lead — license + secrets + isolation
- [ ] Cost owner — budget approved
- [ ] Product owner — SLA acceptable
${plan.kernel_gaps.length > 0 ? `
## Special: kernel gaps detected

This deployment has **${plan.kernel_gaps.length} ops** without native kernel coverage on the target hardware. Either:
1. Codegen the missing kernels (see kernel_gaps.md), validate, then deploy
2. Use fallback path (PyTorch eager / Triton template) — **expect 5-10× slower decode**
3. Switch to a hardware with full coverage (see /operators/hardware-fitness/)

The ops are: ${plan.kernel_gaps.map((g) => g.op).join(', ')}
` : ''}
`;
}

export function generateSBOM(plan: DeploymentPlan): string {
  const r = plan.recommended;
  return JSON.stringify({
    spdxVersion: 'SPDX-2.3',
    SPDXID: 'SPDXRef-DOCUMENT',
    name: `${plan.parsed_model.hf_id} deployment SBOM`,
    documentNamespace: `https://example.com/sbom/${Date.now()}`,
    creationInfo: {
      created: new Date().toISOString(),
      creators: ['Tool: evokernel-spec agent-deploy v2.9']
    },
    packages: [
      {
        SPDXID: 'SPDXRef-Engine',
        name: r.engine,
        versionInfo: 'TODO_PIN',
        downloadLocation: r.engine === 'vllm' ? 'https://github.com/vllm-project/vllm' :
                          r.engine === 'sglang' ? 'https://github.com/sgl-project/sglang' :
                          r.engine === 'tensorrt-llm' ? 'https://github.com/NVIDIA/TensorRT-LLM' :
                          r.engine === 'mindie' ? 'https://www.hiascend.com/document/detail/zh/mindie' : 'NOASSERTION',
        licenseDeclared: 'TODO',
        copyrightText: 'NOASSERTION'
      },
      {
        SPDXID: 'SPDXRef-Model',
        name: plan.parsed_model.hf_id,
        versionInfo: 'TODO_REVISION',
        downloadLocation: `https://huggingface.co/${plan.parsed_model.hf_id}`,
        licenseDeclared: 'TODO_FROM_HF',
        externalRefs: [{
          referenceCategory: 'PACKAGE-MANAGER',
          referenceType: 'purl',
          referenceLocator: `pkg:huggingface/${plan.parsed_model.hf_id}@TODO_REVISION`
        }]
      }
    ],
    relationships: [
      { spdxElementId: 'SPDXRef-DOCUMENT', relationshipType: 'DESCRIBES', relatedSpdxElement: 'SPDXRef-Engine' },
      { spdxElementId: 'SPDXRef-DOCUMENT', relationshipType: 'DESCRIBES', relatedSpdxElement: 'SPDXRef-Model' }
    ]
  }, null, 2);
}
